### PR TITLE
#6 Add an endpoint for deleting logs of an execution

### PR DESCRIPTION
**Pull request by remi-picard**
Implementing [#6](https://github.com/MarketSquare/robotframework-webservice/issues/6)

image

### CODE REVIEW

**Review by Noordsestern — APPROVED** [review]
LGTM

@remi-picard could you resolve the conflict with main branch? It's probably easy, but since the changes on main are yours, too, I do not like to risk resolving the conflict in the wrong way myself :grimacing:

**Comment by remi-picard** [comment]
> LGTM
> 
> @remi-picard could you resolve the conflict with main branch? It's probably easy, but since the changes on main are yours, too, I do not like to risk resolving the conflict in the wrong way myself 😬

I have just rebased my branch onto the main branch and resolve the conflict.

**Comment by Noordsestern** [comment]
One conflict is left in tests/test_app.py

**Comment by remi-picard** [comment]
> One conflict is left in tests/test_app.py... oh, i see! that was the other PR is just merged. Can you fix it again? Sorry 😬

fixed

**Review by Noordsestern — APPROVED** [review]

**Pull request merged**
